namespace WiSJoy.Manager.Audio
{
    /* --------------------WARNING--------------------
    // Do not modify this region
    // Generated by Roslyn
    */
    #region Auto Generators
    public enum MusicID
    {
        None = 0,
        Drama = 1,
        Piano = 2,
    }
    public enum SFXID
    {
        None = 0,
        Bang = 1,
        Blink = 2,
        Victory = 3,
        Glitch = 4,
    }
    public class AudioID
    {
        public static string[] MUSICID = new string[]
    {
        "None",
        "Drama",
        "Piano",
    };


        public static string[] SFXID = new string[]
    {
    "None",
        "Bang",
        "Blink",
        "Victory",
        "Glitch",
    };

    }
    #endregion
}