namespace WiSJoy.UI
{
    /* --------------------WARNING--------------------
    // Do not modify this region
    // Generated by Roslyn
    */
    #region Auto Generators
    public enum eUIID
    {
        None,
    }
    public class UIID
    {
        public static string[] ID = new string[]
        {
            "None",
        };
    }
    #endregion
}