using System;
using WiSdom.SaveSystem.Data;
namespace WiSdom.SaveSystem
{
    /*
        Do not modify this script
    */
    [Serializable]
    public class GameData
    {
        /* --------------------WARNING--------------------
        // Do not modify this region
        // Generated by Roslyn
        */
        #region Auto Generators
        #region Constructor
   		public GameData()
		{
			VersionData = new VersionData();
			PlayerData = new PlayerData();
			DeviceInfo = new DeviceInfo();
			BasicTypeData = new BasicTypeData();
			
		}
		#endregion
        #region Field Generators
		public VersionData VersionData = new VersionData();
		public PlayerData PlayerData = new PlayerData();
		public DeviceInfo DeviceInfo = new DeviceInfo();
		public BasicTypeData BasicTypeData = new BasicTypeData();
		#endregion
        #endregion
    }

}