using Cysharp.Threading.Tasks;
using UnityEngine;
using WiSJoy.DesignPattern;

namespace WiSJoy.Manage.Data
{
	/*
		How to use DataManager:
		1. Declare your data class in DataClass.cs
		2. Open WiSdom -> Data Editor -> follow the instructions -> the code will be generated in this and GameData.cs
		3. Use DataManager to load and save data
		4. Use DataManager. to access your data
		5. Use DataManager.ISALLDATALOADED to check if all data is loaded
		6. Use DataManager.ISDATASAVING to check if data is saving
		7. Use DataManager.ClearAllData() to clear all data
		8. Use DataManager.SaveAllData() to save all data
		9. Use DataManager.LoadAllData() to load all data
		----------------------------------------------
		Should not modify in Auto Generators region
		All fields and methods should be declared in the corresponding region
		----------------------------------------------
		After all, try to save manually in script
	*/
	public class DataManager : SingletonMonoBehaviour<DataManager>
	{
		/*
			All fields are declared here
			No declare fields in other regions
		*/
		#region Fields
		public static bool ISALLDATALOADED = false;
		public static bool ISDATASAVING = false;

		#endregion

		/*
			All methods are declared here
			No declare methods in other regions
		*/
		#region Methods

		protected override void Awake()
		{
			base.Awake();
			Fetch().Forget();
		}
		async UniTask Fetch()
		{
			ISALLDATALOADED = false;
			await LoadAllData();
			// Your data control logic here
			ISALLDATALOADED = true;
		}

		#endregion


		/* --------------------WARNING--------------------
        // Do not modify this region
        // Generated by Roslyn
        */
		#region Auto Generators

		#region Field Generators
		public VersionData VersionData = new VersionData();
		public PlayerData PlayerData = new PlayerData();
		public DeviceInfo DeviceInfo = new DeviceInfo();
		#endregion

		#region Data Control
		public async UniTask LoadAllData()
		{
			#region Load Data
			await LoadVersionDataData();
			await LoadPlayerDataData();
			await LoadDeviceInfoData();
			#endregion
		}
		public async UniTask SaveAllData()
		{
			ISDATASAVING = true;
			#region Save Data
			await SaveVersionDataData();
			await SavePlayerDataData();
			await SaveDeviceInfoData();
			#endregion
			ISDATASAVING = false;
		}
		public void ClearAllData()
		{
			#region Clear Data
			SaveManager.ClearData("VersionData");
			SaveManager.ClearData("PlayerData");
			SaveManager.ClearData("DeviceInfo");
			#endregion
		}
		#endregion
		#region Methods Generators
		public async UniTask LoadVersionDataData()
		{
			VersionData = await SaveManager.LoadData<VersionData>("VersionData");
			if (VersionData is null)
			{
				VersionData = new VersionData();
			}
		}
		public async UniTask SaveVersionDataData()
		{
			await SaveManager.SaveData(VersionData, "VersionData");
		}
		public void ClearVersionDataData()
		{
			SaveManager.ClearData("VersionData");
		}
		public async UniTask LoadPlayerDataData()
		{
			PlayerData = await SaveManager.LoadData<PlayerData>("PlayerData");
			if (PlayerData is null)
			{
				PlayerData = new PlayerData();
			}
		}
		public async UniTask SavePlayerDataData()
		{
			await SaveManager.SaveData(PlayerData, "PlayerData");
		}
		public void ClearPlayerDataData()
		{
			SaveManager.ClearData("PlayerData");
		}
		public async UniTask LoadDeviceInfoData()
		{
			DeviceInfo = await SaveManager.LoadData<DeviceInfo>("DeviceInfo");
			if (DeviceInfo is null)
			{
				DeviceInfo = new DeviceInfo();
			}
		}
		public async UniTask SaveDeviceInfoData()
		{
			await SaveManager.SaveData(DeviceInfo, "DeviceInfo");
		}
		public void ClearDeviceInfoData()
		{
			SaveManager.ClearData("DeviceInfo");
		}
		#endregion
		#endregion
		// --------------------THE END--------------------
	}
}